name: quran_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # STACKED ( STATE MANAGMENT - NAVIGATION - DI)
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  # LOCAL STORAGE
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  path_provider: ^2.1.5
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.26


  # DESIGN
  iconly: ^1.0.1
  flutter_svg: ^2.0.16
  shimmer_animation: ^2.2.2

  # HELPERS
  url_launcher: ^6.3.1
  rxdart: ^0.28.0
  collection: ^1.19.1
  intl: ^0.20.2
  jhijri: ^1.0.0
  jhijri_picker: ^1.0.1

  material_symbols_icons: ^4.2799.0

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true

  assets:
      - assets/quran.json
      - assets/banner.svg
      - assets/icon.png
      - assets/calendar.png
      - assets/fonts/
      - assets/localizations/


  fonts:
      - family: cairo
        fonts:
          - asset: assets/fonts/Cairo-Regular.ttf
          - asset: assets/fonts/Cairo-Light.ttf
            weight: 300
          - asset: assets/fonts/Cairo-Bold.ttf
            weight: 700
      - family: poppins
        fonts:
          - asset: assets/fonts/Cairo-Regular.ttf
      - family: hafs
        fonts:
          - asset: assets/fonts/hafs.ttf


